### ISSUE TITLE
Panic trying to use chunked iterator: `panicked at 'index out of bounds: the len is 8 but the index is 8', src/bitvector.rs:374:16`

### ISSUE THREAD

**Issue by vlovich** [10XGenomics/rust-boomphf#31]
I'm probably misunderstanding how to use the chunked iterator. I have a list of keys but they're in the "wrong" format (i.e. Vec of a different data structure).

I tried:
```
    struct KeyMapper<'a> {
        iter: std::slice::Iter<'a, (u64, Vec<u8>)>,
    }

    impl<'a> Iterator for KeyMapper<'a> {
        type Item = &'a [u8];

        fn next(&mut self) -> Option<Self::Item> {
            let k = self.iter.next().map(|(_, k)| k.as_slice());
            k
        }

        fn nth(&mut self, n: usize) -> Option<Self::Item> {
            self.iter.nth(n).map(|(_, k)| k.as_slice())
        }
    }

    struct KeyGenerator<'a> {
        keys: &'a Vec<(u64, Vec<u8>)>,
    }

    impl<'a> KeyGenerator<'a> {
        fn new(keys: &'a Vec<(u64, Vec<u8>)>) -> Self {
            Self { keys }
        }
    }

    impl<'a, 'c> IntoIterator for &'c KeyGenerator<'a> {
        type Item = &'a [u8];
        type IntoIter = KeyMapper<'a>;

        fn into_iter(self) -> Self::IntoIter {
            KeyMapper {
                iter: self.keys.into_iter(),
            }
        }
    }

    #[test]
    fn from_chunked() {
        let mut values = Vec::new();
        for i in 0..512u32 {
            values.push((i as u64, i.to_be_bytes().into()))
        }

        Mphf::from_chunked_iterator(1.7, &KeyGenerator::new(&values), values.len());
    }
```

but that instantly throws with `thread 'tests::from_chunked' panicked at 'index out of bounds: the len is 8 but the index is 8', src/bitvector.rs:374:16`

Am I incorrectly using the chunked iterator?

**Comment by pmarks** [comment]
The last argument `n` needs to be the total length of all the items that will be yielded by the iterator of iterators. I will update the docs accordingly.

**Comment by vlovich** [comment]
Ah. So in this case it would be 1?

**Comment by pmarks** [comment]
I think it would be 512, right? I can't quite tell how the KeyGenerator / KeyMapper stuff works, but it looks like it will generate at least 512 items.
